config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home_page#index'

  resources :user_plans, only: [ :new, :create ]
  get '/validar/:id', to: 'user_plans#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/type_plan.rb
class TypePlan < ApplicationRecord
  has_many :user_plans
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :user_plans
end

app/models/user_plan.rb
class UserPlan < ApplicationRecord
  belongs_to :user
  belongs_to :type_plan
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/home_page_controller.rb
class HomePageController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  def index
    @plans = TypePlan.all.where(active: true)
    @current_user_plan = helpers.current_plan(current_user)
  end
end

app/controllers/user_plans_controller.rb
class UserPlansController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]

  def show
    user = User.find_by(id: params[:id])
    current_user_plan = helpers.current_plan(user)
    if current_user_plan
      render json: current_user_plan.end_date
    else
      render json: nil
    end
  end

  def new
  end

  def create
    @user_plan = UserPlan.new()
    type_plan = TypePlan.find(params[:type_plan_id])
    @user_plan.type_plan = type_plan
    @user_plan.user = current_user
    @user_plan.start_date = Date.current
    @user_plan.end_date = Date.current + 60

    respond_to do |format|
      if @user_plan.save
        format.html { redirect_to root_path, notice: 'Plan activado' }
        format.json { render :show, status: :created, location: @user_plan }
      else
        format.html { redirect_to root_path, notice: 'Error al activar plan'}
        format.json { render json: @user_plan.errors, status: :unprocessable_entity }
      end
    end
  end


  private

  def user_plan_params
    params.permit(:type_plan_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/user_plans_helper.rb
module UserPlansHelper
  def current_plan(user)
    if user
      user.user_plans.where("start_date <= '#{Date.current}' and end_date >= '#{Date.current}'").first
    end
  end
end

app/views/home_page/index.html.erb
<% if current_user %>
  <h3>Bienvenido: <%= current_user.email %></h3>
  <% if @current_user_plan %>
    <h4>Ya tiene activo el plan: <%= @current_user_plan.type_plan.name %></h4>
    <p>Vencimiento: <%= @current_user_plan.end_date %></p>
  <% else %>
    <h4>No tiene un plan activo</h4>
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <% @plans.each do |plan| %>
        <div class="well well-lg">
          <h4>Plan <%= plan.name %></h4>
          <div class="row">
            <div class="col-md-9">
              <p>Si activas hoy el Plan <%= plan.name %>, tendrá validez hasta el día <%= (Date.current() + 60).to_formatted_s(:iso8601) %></p>
              <p>Precio: <%= number_to_currency(plan.price) %></p>
            </div>
            <div class="col-md-3">
              <%= link_to "Activar", user_plans_path(type_plan_id: plan.id), method: :post, class: "btn btn-primary", data: { confirm: "¿Está seguro de activar este plan? "} %>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  <% end %>
<% else %>
  <div class="jumbotron">
    <h2>Bienvenido a Clud-Business</h2>
    <p class="lead">
      Una nueva forma de administrar su negocio.
    </p>
  </div>

  <div class="row">
    <div class="plans clearfix">
      <div class="col-lg-3 col-lg-offset-3 plan">
        <h2>Plan gratuito</h2>
        <div class="price pull-right">
          Precio: $0
        </div>
        <div class="features">
          <ul>
            <li>Acceso a todas las funciones</li>
            <li>Movimientos y usuarios ilimitados</li>
            <li>Período de prueba: 60 días</li>
          </ul>
        </div>
        <p>
          <%= link_to 'Elegir', new_user_registration_path, class: 'btn btn-primary sign-up' %>
        </p>
      </div>
      <div class="col-lg-3 plan">
        <h2>Plan Premium</h2>
        <div class="price pull-right">
          Precio: $750/mes
        </div>
        <div class="features">
          <ul>
            <li>Todas las funciones del plan gratuito</li>
            <li>Soporte 24x7</li>
            <li>Back-up diarios</li>
            <li class='extra'>Prueba nuevas funciones antes</li>
          </ul>
        </div>
        <p>
          <%= link_to 'Elegir', new_user_registration_path, class: 'btn btn-primary sign-up' %>
        </p>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Negocios" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <%= link_to "Negocios", root_path, class: "navbar-brand" %>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "#" %></li>
            <li><%= link_to "Link2", "#" %></li>
            <li><%= link_to "Link3", "#" %></li>
          </ul>
          <ul class="nav navbar-right col-md-4">
            <% if current_user %>
              <li class="col-md-8 user-name">
                <%= link_to ('<i class="glyphicon glyphicon-user"></i> ' + truncate(current_user.email, length: 25)).html_safe, 
                            edit_user_registration_path, title: "Editar perfil" %>
              </li>
              <li class="col-md-1">&nbsp;</li>
              <li class="col-md-3 logout">
                <%= link_to("Salir", destroy_user_session_path, class: "btn btn-xs- btn-danger", title: "Salir", method: :delete) %>
              </li>
            <% else %>
              <li class="col-md-4 pull-right">
                <%= link_to("Ingresar", new_user_session_path, class: "btn btn-primary", title: "Iniciar sesión") %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <br />
      <footer>
        <p>&copy; Cloud Business 2018</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>